aws:
  s3:
    endpoint: http://localhost:4566   # O http://localhost:9000 para MinIO
    region: us-east-1
    access-key: test
    secret-key: test
    bucket: my-bucket-test

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
